### ISSUE TITLE
A Pytorch impementation

### ISSUE THREAD

**Issue by wddabc** [elikip/bist-parser#11]
Hello, I have implemented a Pytorch version of your parsers (graph-based only). See [here](https://github.com/wddabc/bist-parser). Suggestions and concerns are welcome!

**Comment by neverfox** [comment]
Very cool to see this, given that, among the various dynamic libraries out there, PyTorch seems the one with the most traction/support. I'm working on a port of this myself, though I'm doing a more drastic refactoring. Regarding the multiple root (#10) issue that you routed around, is that basically because the MST approach doesn't really have a solution to that problem as implemented (rather than it being a matter of bugs)?

**Comment by elikip** [comment]
I welcome the pytorch implementation, but if that's not bug please close this issue.

**Comment by wddabc** [comment]
Thanks！
