### ISSUE TITLE
Question about lookup extra values

### ISSUE THREAD

**Issue by danielhers** [elikip/bist-parser#7]
@elikip 
Three elements are added to each lookup table, which I understand correspond to UNKNOWN, PAD and INITIAL. If I understand correctly, UNKNOWN is used for keys that did not occur in training, and PAD is used for missing elements or when word dropout is applied, but when is INITIAL being used?

Also, it seems like the vector for PAD is learned. Why is it so? Shouldn't it be a constant zero vector, as it corresponds to missing elements?

**Comment by neverfox** [comment]
I have the same questions, except I'm not even clear on when either *PAD* or *INITIAL* have any impact in the current code from what I can tell. Is this vestigial?

**Comment by danielhers** [comment]
Sorry, I had gotten a reply personally but didn't summarize it here. _INITIAL_ is indeed vestigial, but _PAD_  is used for missing elements (features referring to non-existent stack elements, for example).

**Comment by neverfox** [comment]
@danielhers Thanks, but I'm looking at the MST parser (I should have made that clear). Since you mention the stack, it's sounds like that might be only something relevant to the transition-based parser, right? And it would also be pointless in the MST parser? I'm guessing there was a lot of copy-pasta (no shame in it) between the two and so some things just don't apply.

**Comment by danielhers** [comment]
Right, I was talking about the transition-based parser. I don't know if these values are used in the MST parser.
